###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    db:
        image: mysql
        container_name: mysql-container
        volumes:
            - /var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=q1w2e3r4
            - MYSQL_DATABASE=mydatabase

    webserver:
        image: 'nginx:alpine'
        container_name: 'nginx'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'

    php-fpm:
        build: phpdocker/php-fpm
        container_name: 'php'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
